### ISSUE TITLE
Doesn't work on Win7 x64

### ISSUE THREAD

**Issue by thezuberat** [dmacpherson/py-interfacelift-downloader#3]
Hi,
I can't get the new script to work - I always get the error: 

```
 "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WGET OUTPUT !!!!!!!!!!!!!!!!!!!!!!!!!!
!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!
------------------------------------------------------------------------
--
Der Befehl "{" ist entweder falsch geschrieben oder
konnte nicht gefunden werden."
```
- in English it means something like "The command "{" is spelled wrong or doesn't exist. "

I try to use the script on Win7 x64. My configuration is:

```
url = 'http://interfacelift.com/wallpaper/downloads/date/2_screens/2880x900/' #Browse to the page that has all the wallpaper you want and paste here
directory = 'c:/stick/' #Path to download to
stoponfind = '1' # Set to 0 to download all files even if the file exists and 1 to stop when it finds where it left off
wgetpath = 'wget' #Default on linux systems /usr/local/bin/wget on freebsd
```

but I also tried:

```
wgetpath = 'wget.exe' #Default on linux systems /usr/local/bin/wget on freebsd
```

and:

```
wgetpath = 'c:/python27/wget.exe' #Default on linux systems /usr/local/bin/wget on freebsd
```

(the wget.exe is located in c:/python27/wget.exe).

Any help would be appreciated.

**Comment by dmacpherson** [comment]
thezuberat, I'd make sure you're escaping the path for windows correctly. I believe windows wants 'c:\path\to\file'. I do not have python setup on a windows box to test this though.

**Comment by dmacpherson** [comment]
Er, it removed my double \ \ in the path on the comment. Check the link below.

http://stackoverflow.com/questions/204017/how-do-i-execute-a-program-from-python-os-system-fails-due-to-spaces-in-path
