### ISSUE TITLE
Why use wget when you already import urllib2?

### ISSUE THREAD

**Issue by eyyit** [dmacpherson/py-interfacelift-downloader#4]

**Comment by dmacpherson** [comment]
I remember having a reason when I first set it up but I can't remember what it was. If you think urllib2 would work better for that part, work up some code for it and submit a change. I'll see about updating this repo with it if it has all of the same functionality.

**Comment by eyyit** [comment]
I rewrote it here: https://github.com/Alives/py-interfacelift-downloader

**Comment by dmacpherson** [comment]
That looks pretty good! I'll have to play with it when I get some free time.
